on:
  push:
    branches:
      - master

jobs:
  cleanliness:
    name: Cleanliness Checks
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2

      - name: Install Doxygen and Graphviz ğŸ“¥
        run: sudo apt-get -y install doxygen graphviz

      - name: Fast Setup ğŸ“¦
        run: ./setup --generate-location-file

      - name: Documentation ğŸ“–
        working-directory: projects/continuous_integration
        run: make doxygen

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: documentation # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
